server:
  port: 8083

spring:
  application:
    name: notification-service


kafka:
  bootstrapAddress: localhost:9092
  topic:
    name: bookingData
  consumer:
    group:
      id: bookingData-group-id

user:
  url: http://USER-SERVICE/users/v1/

play:
  url: http://INVENTORY-SERVICE/play/v1/
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/