server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movieapp?useSSL=true
    username: root
    password: root
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      
  application:
    name: booking-service

user:
  url: http://USER-SERVICE/users/

play:
  url: http://INVENTORY-SERVICE/play/
      
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token
    client:
      client-id: movieapp
      client-secret: secret

kafka:
  bootstrapAddress: localhost:9092
  topic:
    name: bookingData

auth:
  link: http://localhost:8081/oauth/token

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logstash:
  host: localhost
  port: 5044