server:
  port: 8084
  
spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
  application:
    name: search-service


security:
  oauth2:
    client:
      client-id: movieapp
      client-secret: secret

auth:
  link: http://localhost:8081/oauth/token

          
play:
  url: http://localhost:8080/play/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  