server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movieapp?useSSL=true
    username: root
    password: root
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      
  application:
    name: user-service

security:
  oauth2:
    client:
      client-id: movieapp
      client-secret: secret

auth:
  link: http://localhost:8081/oauth/token

    
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

