server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movieapp?useSSL=true
    username: root
    password: root
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      
  application:
    name: inventory-service
    
security:
  basic:
    enabled: false
  oauth2:
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token
    client:
      client-id: movieapp
      client-secret: secret

auth:
  link: http://localhost:8081/oauth/token

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logstash:
  host: localhost
  port: 5044
 
  

  